create table ComunidadAutonoma(
ID int not null auto_increment primary key,
CodigoINE varchar(4),
Nombre varchar(60),
Activo int not null default(1),
FechaCreacion datetime not null default now(),
FechaModificacion datetime not null default now()
);



insert into ComunidadAutonoma (CodigoINE, Nombre)
values ('01','Andalucía'),
('02','Aragón'),
('03','Asturias, Principado de'),
('04','Balears, Illes'),
('05','Canarias'),
('06','Cantabria'),
('07','Castilla y León'),
('08','Castilla - La Mancha'),
('09','Cataluña'),
('10','Comunitat Valenciana'),
('11','Extremadura'),
('12','Galicia'),
('13','Madrid, Comunidad de'),
('14','Murcia, Región de'),
('15','Navarra, Comunidad Foral de'),
('16','País Vasco'),
('17','Rioja, La'),
('18','Ceuta'),
('19','Melilla');


create table Provincia(
ID int not null auto_increment primary key,
IDComunidadAutonoma int not null,
CodigoINE varchar(4),
Nombre varchar(60),
Activo int not null default(1),
FechaCreacion datetime not null default now(),
FechaModificacion datetime not null default now(),
FOREIGN KEY (IDComunidadAutonoma) REFERENCES comunidadAutonoma(ID)
);

insert into Provincia (IDComunidadAutonoma ,CodigoINE, Nombre) values
((select id from comunidadAutonoma where codigoINE = '01'),'04','Almería'),
((select id from comunidadAutonoma where codigoINE = '01'),'11','Cádiz'),
((select id from comunidadAutonoma where codigoINE = '01'),'14','Córdoba'),
((select id from comunidadAutonoma where codigoINE = '01'),'18','Granada'),
((select id from comunidadAutonoma where codigoINE = '01'),'21','Huelva'),
((select id from comunidadAutonoma where codigoINE = '01'),'23','Jaén'),
((select id from comunidadAutonoma where codigoINE = '01'),'29','Málaga'),
((select id from comunidadAutonoma where codigoINE = '01'),'41','Sevilla'),
((select id from comunidadAutonoma where codigoINE = '02'),'22','Huesca'),
((select id from comunidadAutonoma where codigoINE = '02'),'44','Teruel'),
((select id from comunidadAutonoma where codigoINE = '02'),'50','Zaragoza'),
((select id from comunidadAutonoma where codigoINE = '03'),'33','Asturias'),
((select id from comunidadAutonoma where codigoINE = '04'),'07','Balears, Illes'),
((select id from comunidadAutonoma where codigoINE = '05'),'35','Palmas, Las'),
((select id from comunidadAutonoma where codigoINE = '05'),'38','Santa Cruz de Tenerife'),
((select id from comunidadAutonoma where codigoINE = '06'),'39','Cantabria'),
((select id from comunidadAutonoma where codigoINE = '07'),'05','Ávila'),
((select id from comunidadAutonoma where codigoINE = '07'),'09','Burgos'),
((select id from comunidadAutonoma where codigoINE = '07'),'24','León'),
((select id from comunidadAutonoma where codigoINE = '07'),'34','Palencia'),
((select id from comunidadAutonoma where codigoINE = '07'),'37','Salamanca'),
((select id from comunidadAutonoma where codigoINE = '07'),'40','Segovia'),
((select id from comunidadAutonoma where codigoINE = '07'),'42','Soria'),
((select id from comunidadAutonoma where codigoINE = '07'),'47','Valladolid'),
((select id from comunidadAutonoma where codigoINE = '07'),'49','Zamora'),
((select id from comunidadAutonoma where codigoINE = '08'),'02','Albacete'),
((select id from comunidadAutonoma where codigoINE = '08'),'13','Ciudad Real'),
((select id from comunidadAutonoma where codigoINE = '08'),'16','Cuenca'),
((select id from comunidadAutonoma where codigoINE = '08'),'19','Guadalajara'),
((select id from comunidadAutonoma where codigoINE = '08'),'45','Toledo'),
((select id from comunidadAutonoma where codigoINE = '09'),'08','Barcelona'),
((select id from comunidadAutonoma where codigoINE = '09'),'17','Girona'),
((select id from comunidadAutonoma where codigoINE = '09'),'25','Lleida'),
((select id from comunidadAutonoma where codigoINE = '09'),'43','Tarragona'),
((select id from comunidadAutonoma where codigoINE = '10'),'03','Alicante/Alacant'),
((select id from comunidadAutonoma where codigoINE = '10'),'12','Castellón/Castelló'),
((select id from comunidadAutonoma where codigoINE = '10'),'46','Valencia/València'),
((select id from comunidadAutonoma where codigoINE = '11'),'06','Badajoz'),
((select id from comunidadAutonoma where codigoINE = '11'),'10','Cáceres'),
((select id from comunidadAutonoma where codigoINE = '12'),'15','Coruña, A'),
((select id from comunidadAutonoma where codigoINE = '12'),'27','Lugo'),
((select id from comunidadAutonoma where codigoINE = '12'),'32','Ourense'),
((select id from comunidadAutonoma where codigoINE = '12'),'36','Pontevedra'),
((select id from comunidadAutonoma where codigoINE = '13'),'28','Madrid'),
((select id from comunidadAutonoma where codigoINE = '14'),'30','Murcia'),
((select id from comunidadAutonoma where codigoINE = '15'),'31','Navarra'),
((select id from comunidadAutonoma where codigoINE = '16'),'01','Araba/Álava'),
((select id from comunidadAutonoma where codigoINE = '16'),'48','Bizkaia'),
((select id from comunidadAutonoma where codigoINE = '16'),'20','Gipuzkoa'),
((select id from comunidadAutonoma where codigoINE = '17'),'26','Rioja, La'),
((select id from comunidadAutonoma where codigoINE = '18'),'51','Ceuta'),
((select id from comunidadAutonoma where codigoINE = '19'),'52','Melilla');
